version: "3.1"

services:
  postgres-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    container_name: postgres-container
    image: postgres-image:latest
    restart: always
    ports:
      - "5433:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.multi
      target: server
    container_name: server-container
    # image: server-image:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - postgres-service

  client-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.multi
      target: client
    container_name: client-container
    # image: client-image:latest
    restart: always
    networks:
      - my_network
    depends_on:
      - server-service

volumes:
  postgres_data:

networks:
  my_network:
    external: true
