FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    cmake \
    make \
    build-essential \
    python3 \
    python3-pip \
    libboost-all-dev \
    && apt-get clean

ENV PATH /root/.local/bin:$PATH
RUN pip3 install conan
ENV PATH /root/.conan/bin:$PATH
RUN conan profile detect --force

WORKDIR /app
COPY . .

ENV DOCKER_CONTAINER true

WORKDIR /app/src/App-Client
RUN make build

CMD ["/app/src/App-Client/build/exe"]